### ISSUE TITLE
AttributeError: 'document' object has no attribute 'findall' on Sphinx <4.4

### ISSUE THREAD

**Issue by marcelm** [GeeTransit/sphinx-better-subsection#1]
Hi, thanks a lot for creating this!

I ran into a crash when trying it out on one of my projects:
```
Exception occurred:
  File ".../.venv/lib/python3.8/site-packages/sphinx_better_subsection.py", line 64, in apply
    for node in self.document.findall(nodes.section):
AttributeError: 'document' object has no attribute 'findall'
```
I’m opening this issue only to document that this occurred on Sphinx 4.3 and was fixed by updating Sphinx to at least version 4.4.

**Comment by GeeTransit** [comment]
Thanks for filing this issue :D

Seems like [Sphinx 4.4 monkey-patches][1] the `.findall` method for docutils<0.18, which is why it didnt work on Sphinx 4.3, and also why I didn't experience this because I use 4.4. `.traverse` looks like the equivalent API for docutils<0.18. I'll push a fix and create a new release for this shortly.

[1]: https://github.com/sphinx-doc/sphinx/commit/05a898ecb4ff8e654a053a1ba5131715a4514812#diff-8a06a6233264b57f905c460f3a647e5e55246f2e6ba9f0ed4deb87adb68c85d1

**Comment by marcelm** [comment]
Nice, thanks!
